name: expense_manager
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15
  go_router: ^6.5.3
  currency_text_input_formatter: ^2.1.9
  dropdown_search: ^5.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
